# Generated by Django 5.1.2 on 2024-11-04 14:05

import apps.love_fauna.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_fauna', '0002_pet_descricao_alter_pet_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, validators=[apps.love_fauna.validators.birthday_valid]),
        ),
        migrations.AddField(
            model_name='pet',
            name='creat_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
