# Generated by Django 5.1.2 on 2024-11-08 14:18

import apps.users.consulta_ibge
import apps.users.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('BR', 'Brasil')], max_length=2)),
                ('zip_code', models.CharField(max_length=8)),
                ('state', models.CharField(choices=apps.users.consulta_ibge.unidade_federativa, max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_name', models.CharField(max_length=100)),
                ('responsible_cpf', models.CharField(max_length=11, unique=True)),
                ('responsible_phone', models.CharField(max_length=15)),
                ('responsible_email', models.EmailField(max_length=150)),
                ('responsible_birthday', models.DateField(default=django.utils.timezone.localdate, validators=[apps.users.validators.birthday_valid])),
                ('shelter_name', models.CharField(max_length=100)),
                ('shelter_cnpj', models.CharField(max_length=14, unique=True, validators=[apps.users.validators.cnpj_validator])),
                ('shelter_phone', models.CharField(max_length=15)),
                ('shelter_email', models.EmailField(max_length=150)),
                ('terms', models.BooleanField(default=False)),
                ('creat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[apps.users.validators.cpf_validator])),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('birthday', models.DateField(default=django.utils.timezone.localdate, validators=[apps.users.validators.birthday_valid])),
                ('terms', models.BooleanField(default=False)),
                ('creat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
        ),
    ]
