# Generated by Django 5.1.2 on 2024-11-11 17:10

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shelter_password_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='password',
            field=models.CharField(default=False, max_length=100, validators=[apps.users.validators.senha_safety]),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='responsible_birthday',
            field=models.DateField(default=False, validators=[apps.users.validators.birthday_valid]),
        ),
    ]
