# Generated by Django 5.1.2 on 2024-11-11 17:13

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_shelter_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='password',
            field=models.CharField(max_length=100, validators=[apps.users.validators.senha_safety]),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='responsible_birthday',
            field=models.DateField(validators=[apps.users.validators.birthday_valid]),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='terms',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(validators=[apps.users.validators.birthday_valid]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[apps.users.validators.senha_safety]),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms',
            field=models.BooleanField(),
        ),
    ]
